using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Download_Manager
{
    public class Listing
    {
        // List of categories
        public List<Category> categories = new List<Category>();

        // Array of category names
        public string[] categoryName = new string[] 
        {   "Web Browsers",
            "File Sharing",
            "Compression",
            "Messaging",
            "Online Storage",
            "Media",
            "Runtimes",
            "Other",
            "Imaging",
            "Developer Tools",
            "Documents",
            "Utilities",
            "Security"
        };

        /// <summary>
        /// Add the categories to the list
        /// </summary>
        public void InitializeCategories()
        {
            for (int i = 0; i < categoryName.Length; i++)
            {
                // Name, ID
                // ID may become obsolete
                Category category = new Category(categoryName[i], i);
                categories.Add(category);
            }
        }

        // List of programss
        public List<Programs> programs = new List<Programs>();

        // Array of browser names, 86 programs
        public string[] programName = new string[]
        {   "Google Chrome",    // Web Browsers
            "Mozilla Firefox",
            "Opera",
            "Microsoft Edge",
            "Vivaldi",
            "Safari",
            "qBittorent",       // File Sharing
            "eMule",
            "7-Zip",            // Compression
            "PeaZip",
            "WinRAR",
            "Skype",            // Messaging
            "Pidgin",
            "Thunderbird",
            "Trillian",
            "AIM",
            "Dropbox",          // Online Storage
            "Google Drive",
            "Mozy",
            "OneDrive",
            "SugarSync",
            "iTunes",           // Media
            "VLC",
            "AIMP",
            "foobar2000",
            "Winamp",
            "MusicBee",
            "Audacity",
            "K-Lite Codecs",
            "GOM",
            "CCCP",
            "MediaMonkey",
            "HandBrake",
            "Java 8",           // Runtimes
            ".NET 4.6.2",
            "Silverlight",
            "Air",
            "Shockwave",
            "Evernote",         // Other
            "Google Earth",
            "Steam",
            "KeePass 2",
            "Everything",
            "NV Access",
            "Paint.NET",        // Imaging
            "GIMP",
            "IrfanView",
            "XnView",
            "InkScape",
            "FastStone",
            "Greenshot",
            "ShareX",
            "Python",           // Developer Tools
            "FileZilla",
            "Notepad++",
            "JDK 8",
            "JDK x64 8",
            "WinSCP",
            "PuTTY",
            "WinMerge",
            "Eclipse",
            "Visual Studio Code",
            "Foxit Reader",     // Documents
            "LibreOffice",
            "SumatraPDF",
            "CutePDF",
            "PDFCreator",
            "OpenOffice",
            "Teamviewer 12",    // Utilities
            "ImgBurn",
            "RealVNC",
            "TeraCopy",
            "CDBurnerXP",
            "Revo",
            "Launchy",
            "WinDirStat",
            "Glary",
            "InfraRecorder",
            "Classic Start",
            "Essentials",       // Security
            "Avast",
            "AVG",
            "Malwarebytes",
            "Ad-Aware",
            "Spybot 2",
            "Avira",
            "SUPERAntiSpyware",
        };

        // Array of browser names
        public string[] programCategory = new string[]
        {   "Web Browsers",
            "Web Browsers",
            "Web Browsers",
            "Web Browsers",
            "Web Browsers",
            "Web Browsers",
            "File Sharing",
            "File Sharing",
            "Compression",
            "Compression",
            "Compression",
            "Messaging",
            "Messaging",
            "Messaging",
            "Messaging",
            "Messaging",
            "Online Storage",
            "Online Storage",
            "Online Storage",
            "Online Storage",
            "Online Storage",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Media",
            "Runtimes",
            "Runtimes",
            "Runtimes",
            "Runtimes",
            "Runtimes",
            "Other",
            "Other",
            "Other",
            "Other",
            "Other",
            "Other",
            "Imaging",
            "Imaging",
            "Imaging",
            "Imaging",
            "Imaging",
            "Imaging",
            "Imaging",
            "Imaging",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Developer Tools",
            "Documents",
            "Documents",
            "Documents",
            "Documents",
            "Documents",
            "Documents",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Utilities",
            "Security",
            "Security",
            "Security",
            "Security",
            "Security",
            "Security",
            "Security",
            "Security"
        };

        // Array of browser URL's
        public string[] programUrl = new string[]
        {   "http://dl.google.com/tag/s/appguid=%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D&iid=%7BB7F9A059-3A71-F0A8-67CB-8C83969F881C%7D&lang=en-IN&browser=3&usagestats=0&appname=Google%20Chrome&needsadmin=false/update2/installers/ChromeStandaloneSetup.exe",
            "https://download.mozilla.org/?product=firefox-stub&amp;os=win&amp;lang=sv-SE",
            "Compression",
            "Messaging",
            "Online Storage",
            "Media",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        };

        // Array of browser descriptions
        public string[] programDesc = new string[]
        {   "The world's most popular web browser.",
            "Open source.",
            "Based on chrome.",
            "Microsofts modern browser.",
            "A new customizable browser.",
            "Apple's web browser.",
            "Descriptiuon for qBittorrent",
            "Description for eMule",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        };

        /// <summary>
        /// Add the browsers to the list
        /// </summary>
        public void InitializePrograms()
        {
            for (int i = 0; i < programName.Length; i++)
            {
                // Name, ID, CategoryID, URL, Description
                // The CategoryID is used to display the correct programs
                // ID may become obsolete

                Programs program = new Programs(programName[i], i, programCategory[i], programUrl[i], programDesc[i]);
                programs.Add(program);
            }
        }
    }
}
